### ISSUE TITLE
BSONError: cyclic dependency detected

### ISSUE THREAD

**Issue by QuentinGruber** [QuentinGruber/h1z1-server#1060]
Unhandled rejection at  Promise {
  <rejected> BSONError: cyclic dependency detected
      at new BSONError (/usr/src/app/node_modules/bson/lib/error.js:23:28)
      at serializeObject (/usr/src/app/node_modules/bson/lib/parser/serializer.js:267:19)
      at serializeInto (/usr/src/app/node_modules/bson/lib/parser/serializer.js:810:25)
      at serializeObject (/usr/src/app/node_modules/bson/lib/parser/serializer.js:280:20)
      at serializeInto (/usr/src/app/node_modules/bson/lib/parser/serializer.js:810:25)
      at serializeObject (/usr/src/app/node_modules/bson/lib/parser/serializer.js:280:20)
      at serializeInto (/usr/src/app/node_modules/bson/lib/parser/serializer.js:810:25)
      at serializeObject (/usr/src/app/node_modules/bson/lib/parser/serializer.js:280:20)
      at serializeInto (/usr/src/app/node_modules/bson/lib/parser/serializer.js:810:25)
      at serializeObject (/usr/src/app/node_modules/bson/lib/parser/serializer.js:280:20)
} reason: BSONError: cyclic dependency detected at Tue Aug 23 2022 16:45:05 GMT+0000 (Coor
dinated Universal Time)

**Comment by QuentinGruber** [comment]
It happen when the server save when you're reloading
