### ISSUE TITLE
parsing issue

### ISSUE THREAD

**Issue by QuentinGruber** [QuentinGruber/h1z1-server#1399]
```
Synchronization : RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 14. Received 16
TypeError: Cannot read properties of undefined (reading 'clientTime')
    at zonePacketHandlers.Synchronization (/usr/src/app/node_modules/h1z1-server/out/servers/ZoneServer2016/zonepackethandlers.js:402:64)
    at zonePacketHandlers.processPacket (/usr/src/app/node_modules/h1z1-server/out/servers/ZoneServer2016/zonepackethandlers.js:1586:22)
    at LiveZoneServer.onZoneDataEvent (/usr/src/app/node_modules/h1z1-server/out/servers/ZoneServer2016/zoneserver.js:332:34)
    at LiveZoneServer.emit (node:events:513:28)
    at GatewayServer.<anonymous> (/usr/src/app/node_modules/h1z1-server/out/servers/ZoneServer2016/zoneserver.js:216:22)
    at GatewayServer.emit (node:events:513:28)
    at SOEServer.<anonymous> (/usr/src/app/node_modules/h1z1-server/out/servers/GatewayServer/gatewayserver.js:57:34)
    at SOEServer.emit (node:events:513:28)
    at SOEInputStream.<anonymous> (/usr/src/app/node_modules/h1z1-server/out/servers/SoeServer/soeserver.js:280:30)
    at SOEInputStream.emit (node:events:513:28)
An error occurred while processing a packet :  { name: 'Synchronization', data: undefined }
h1z1-server version : 0.24.1-2
unknown flag used : 4 for packet : 32
unknown flag used : 4 for packet : 82
unknown flag used : 7 for packet : 251
unknown packet use flag 3 : 222
unknown flag used : 7 for packet : 72
Gateway: packet parsing failed
<Buffer 01 0d 7f c4 7b 38 f4 92 5d 6c 23 16 4b 1b c3 45>
RuntimeError: unreachable
    at wasm://wasm/000c773e:wasm-function[249]:0x2721d
    at wasm://wasm/000c773e:wasm-function[297]:0x294aa
    at wasm://wasm/000c773e:wasm-function[392]:0x2b5f5
    at wasm://wasm/000c773e:wasm-function[350]:0x2aaad
    at wasm://wasm/000c773e:wasm-function[379]:0x2b345
    at wasm://wasm/000c773e:wasm-function[324]:0x2a144
    at wasm://wasm/000c773e:wasm-function[435]:0x2baed
    at wasm://wasm/000c773e:wasm-function[220]:0x25731
    at wasm://wasm/000c773e:wasm-function[49]:0xdee2
    at wasm://wasm/000c773e:wasm-function[283]:0x28b68
```

**Comment by QuentinGruber** [comment]
https://github.com/H1emu/h1emu-core/issues/27

**Comment by QuentinGruber** [comment]
https://github.com/QuentinGruber/h1z1-server/pull/1431
