### ISSUE TITLE
Uncaught Exception: Cannot read properties of undefined (reading 'nameId')

### ISSUE THREAD

**Issue by QuentinGruber** [QuentinGruber/h1z1-server#1903]
```
Uncaught Exception: Cannot read properties of undefined (reading 'nameId') time : Sun Feb 04 2024 08:04:15 GMT+0000 (Coordinated Universal Time)
TypeError: Cannot read properties of undefined (reading 'nameId')
    at /usr/src/app/node_modules/h1z1-server/out/servers/ZoneServer2016/zoneserver.js:5521:45
    at Array.forEach (<anonymous>)
    at LiveZoneServer.sendHudIndicators (/usr/src/app/node_modules/h1z1-server/out/servers/ZoneServer2016/zoneserver.js:5515:48)
    at /usr/src/app/node_modules/h1z1-server/out/servers/ZoneServer2016/entities/character.js:321:24
    at Array.forEach (<anonymous>)
    at Character2016.updateResources (/usr/src/app/node_modules/h1z1-server/out/servers/ZoneServer2016/entities/character.js:313:28)
    at Timeout._onTimeout (/usr/src/app/node_modules/h1z1-server/out/servers/ZoneServer2016/entities/character.js:170:67)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
```

**Comment by QuentinGruber** [comment]
will reopen another one when we have better logs of this
