### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '_clients')

### ISSUE THREAD

**Issue by QuentinGruber** [QuentinGruber/h1z1-server#2147]
TypeError: Cannot read properties of undefined (reading '_clients')
    at LiveLoginServer.rejectZoneConnection (/usr/src/app/out/loginserver.js:32:43)
    at ZoneConnectionManager.<anonymous> (/usr/src/app/node_modules/h1z1-server/out/servers/LoginServer/loginserver.js:165:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by QuentinGruber** [comment]
was fixed on https://github.com/H1emu/live-login-server
