### ISSUE TITLE
a wasm error isn't handled and make the whole server enter a weird state

### ISSUE THREAD

**Issue by QuentinGruber** [QuentinGruber/h1z1-server#804]
Error: recursive use of an object detected which would lead to unsafe aliasing in rust
    at module.exports.__wbindgen_throw (/usr/src/app/node_modules/h1emu-core/h1emu_core.js:495:11)
    at wasm://wasm/000ba1ce:wasm-function[274]:0x27849
    at wasm://wasm/000ba1ce:wasm-function[273]:0x2783e
    at wasm://wasm/000ba1ce:wasm-function[152]:0x25430
    at Soeprotocol.parse (/usr/src/app/node_modules/h1emu-core/h1emu_core.js:326:18)
    at Worker.<anonymous> (/usr/src/app/node_modules/h1z1-server/out/servers/SoeServer/soeserver.js:269:60)
    at Worker.emit (node:events:526:28)
    at MessagePort.<anonymous> (node:internal/worker:232:53)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:647:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)

**Comment by QuentinGruber** [comment]
linked to https://github.com/H1emu/h1emu-core/issues/9
